In [ ]:
#1. Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result
import numpy as np
# Given list
my_list = [1, 2, 3, 4, 5]
# Convert list to NumPy array
arr = np.array(my_list)
# Display the array
print("Array:", arr)
# Display the first and last element
print("First element:", arr[0])
print("Last element:", arr[-1])
# Multiply each element by 2 and display the result
doubled_arr = arr * 2
print("Array after doubling each element:")
print(doubled_arr)

Array: [1 2 3 4 5]
First element: 1
Last element: 5
Array after doubling each element:
[ 2  4  6  8 10]


In [ ]:
#2. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.
import numpy as np
# Create an array of 10 zeros
zeros_array = np.zeros(10)
print("An array of 10 zeros:")
print(zeros_array)
# Create an array of 10 ones
ones_array = np.ones(10)
print("\nAn array of 10 ones:")
print(ones_array)
# Create an array of 10 fives
fives_array = np.full(10, 5)
print("\nAn array of 10 fives:")
print(fives_array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

An array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#3. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
import numpy as np
# Create a 3x3 matrix with values ranging from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 matrix with values from 2 to 10:")
print(matrix)

3x3 matrix with values from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
